### PR TITLE
remove version restriction

### PR DESCRIPTION
**Pull request by melund**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by melund** [comment]
@conda-forge-admin, please rerender

**Comment by melund** [comment]
@jjnurminen It didn't seem to work. I will just try to remove the python3 patch when building on 2.7.

**Comment by melund** [comment]
@jjnurminen  It fails with a CMAKE problem. I guess it can be solved, but I don't have time :)
 
```
CMake Error at D:/bld/btk_1579008878392/_build_env/Library/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find NumPy (missing: NUMPY_VERSION NUMPY_INCLUDE_DIR)
Call Stack (most recent call first):
  D:/bld/btk_1579008878392/_build_env/Library/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  CMake/FindNumPy.cmake:31 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  Wrapping/Python/CMakeLists.txt:4 (FIND_PACKAGE)

```

**Comment by jjnurminen** [comment]
Ok, thanks a lot for your efforts. Maybe I'll dig into it at some point.

**Pull request closed without merging**
